# Generated by Django 2.1.4 on 2018-12-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("manager", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="injectedemailcontent",
            options={
                "verbose_name": "My Injected Email",
                "verbose_name_plural": "My Injected Emails",
            },
        ),
        migrations.AlterField(
            model_name="email",
            name="email_list",
            field=models.ManyToManyField(to="manager.EmailCategory"),
        ),
        migrations.AlterField(
            model_name="emailcategory",
            name="mailing_list",
            field=models.ManyToManyField(related_name="user", to="manager.EmailList"),
        ),
    ]
