# Generated by Django 2.1.4 on 2018-12-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("manager", "0003_auto_20181207_1836")]

    operations = [
        migrations.AlterField(
            model_name="emailcategory",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        )
    ]
